DELETE FROM employees;
DELETE FROM departments;
CALL add_department(1,'Sales');
CALL add_department(2,'IT');
CALL add_department(3,'Compliance');
CALL add_department(4,'Research');
CALL add_department(5,'HR');
insert into employees (eid, ename, email, did, kind) values (1, 'Clo Allright', 'callright0@deviantart.com', 2, 1);
insert into employees (eid, ename, email, did, kind) values (2, 'Innis Varvara', 'ivarvara1@arstechnica.com', 3, 2);
insert into employees (eid, ename, email, did, kind) values (3, 'Elspeth Dumbrell', 'edumbrell2@mashable.com', 4, 0);
insert into employees (eid, ename, email, did, kind) values (4, 'Jean Leeman', 'jleeman3@ftc.gov', 5, 1);
CALL add_employee('Antonie Reightley', 'areightley4@google.fr', 4, 2, 123);
CALL add_employee('Ranna Donoher', 'rdonoher5@tmall.com', 3, 0, 456);
CALL add_employee('Hew Huckfield', 'hhuckfield6@plala.or.jp', 2, 1, 789);
CALL add_employee('Cecil Concannon', 'cconcannon7@nifty.com', 5, 2, 101112);
SELECT * FROM departments;
SELECT * FROM employees;
SELECT * FROM econtacts;
CALL add_department(6,'Supply Chain');
CALL add_department(7,'Support');
CALL add_department(8,'Transport');
CALL add_department(9,'Cleanliness');
CALL add_department(10,'Finance');
SELECT * FROM departments;
SELECT * FROM employees;
SELECT * FROM econtacts;
CALL remove_department(2);
CALL add_room(1,2,'12',5,4,'2021-11-03', 5);